### PR TITLE
Implement Entry Page and Make it Purty

### PR DESCRIPTION
**Pull request by MrMagma**
This PR implements the entry page adding the necessary controls and makes them purty too.
# Major Changes
## entry.html
- Add program controls for width, height, reloading the program, etc. They don't do anything right now except look good.
## sass/main.scss
- Add styles for all of the elements added to the entry page
## src/client/entry.js
- Eliminate a switch statement and make the `createJudgingControl` method slightly more maintainable.
- Add code to put our rubric controls on the page
- Add a `createRubricTab` method to create tabs for rubrics so the code looks slightly cleaner.
# Minor Changes
## build/src/_shared.js
- Update the text of the footer so that it now has the current name of this project

Thank you for your time!

### CODE REVIEW

**Comment by bytorbrynden** [comment]
PR looks good, aside from the merge conflicts. Ping me when you get those resolved and we can merge this.

**Comment by MrMagma** [comment]
Merge conflicts fixed. I've taken some screenshots for review of the visual changes.

Desktop

http://prntscr.com/8zfylx

Mobile

http://prntscr.com/8zfzhm

http://prntscr.com/8zfz4y

The layout for mobile still needs a bit of work, not top priority though.

**Comment by bytorbrynden** [comment]
Looks awesome! Merging.

**Comment by bytorbrynden** [comment]
Thanks for the PR!

**Pull request merged**
