### PR TITLE
Fixed critical error of typo

### PR DESCRIPTION
**Pull request by Noble-Mushtak**
You forgot a `/` in the link to the entries in `Client/scripts/contest.js` and that messed up all of the links to the entries. Also, don't use `$(function() { [...] })` in a `<script>` at the end of a document because `$()` is only for binding a function to the `onload` event but at that point, you don't need it because the document has already almost loaded.

However, I really like where we are going with this! This is really coming together!

### CODE REVIEW

**Comment by Noble-Mushtak** [comment]
Oh wait...You _just_ fixed it...

**Comment by bytorbrynden** [comment]
Just noticed that as well when testing! Fixed in https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/eb7a9b03d201b27486fefac2a3af66a6c69ce3e3.

**Comment by Noble-Mushtak** [comment]
Can you please still merge this to get rid of `$()`? (Or you could do it manually if that's faster.)

**Comment by bytorbrynden** [comment]
https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/38ea5ef289a37390fefb5e626f4a510747a7f06a

**Comment by Noble-Mushtak** [comment]
Yay! Now this can be closed!

**Pull request closed without merging**
