### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by darrylyeo**
Concatenated `.addClass()` calls.

Returns nodes directly instead of making variables.

Mobile responsive.

### CODE REVIEW

**Comment by MrMagma** [comment]
Looks good.

**Comment by bytorbrynden** [comment]
Just made a first-pass through this; it's looking good so far. I like that, as-per this PR, we'd be returning the jQuery collections directly, rather than declaring variables for them, and returning the variables.

**Comment by bytorbrynden** [comment]
Can you change `@contributor` to `@contributors` on lines 7, 22, and 42 of `index.js`?

**Comment by darrylyeo** [comment]
Sure.

**Comment by bytorbrynden** [comment]
Thanks for the PR @darrylyeo. :shipit:

**Pull request merged**
