### PR TITLE
Made Application Example and Added `getApi()`

### PR DESCRIPTION
**Pull request by Noble-Mushtak**
OK, so I got a pull request to my repo to add a `getApi()` function which I merged into my `master` branch:
https://github.com/aikaikaik/KA-Contest-Judging-System/commit/dee9bceaef6c6fc8abf8437d76882e5cfca81718

I also made an application example where you can browse through contests and contest entries. Look at `tests/app.css`, `tests/app.js`, `tests/app.html`.

### CODE REVIEW

**Comment by bytorbrynden** [comment]
Is there another fork/PR where @aikaikaik created the the `getApi` function?

**Comment by Noble-Mushtak** [comment]
Yes, he made it on a fork of my fork [here](https://github.com/aikaikaik/KA-Contest-Judging-System).

**Comment by bytorbrynden** [comment]
I would merge this right now @Noble-Mushtak, however there appears to be some conflicts. I'll try and fix those tomorrow, and then merge.

Thanks for the PR!

**Comment by Noble-Mushtak** [comment]
Oh, the conflicts were minor so I was able to fix them easily. In fact, I merged my repo with this repo _before_ you said that!

**Comment by bytorbrynden** [comment]
Oh, great! I'll see about merging this in the morning! :)

**Comment by Noble-Mushtak** [comment]
Can we please merge these repos? I have more documentation (comments) in my repo and everytime I try to merge our repos, there's some conflict which makes it slower to merge.

**Comment by bytorbrynden** [comment]
I've been holding back on merging because your version has a lot of things that I'm not quite ready for just yet... Like I said, I'll go through all your stuff later today.

**Comment by Noble-Mushtak** [comment]
OK, as long as it's done soon, not necessarily immediately.

**Comment by Noble-Mushtak** [comment]
Just so you know, I _highly_ suggest just using Git to merge these two repos (although you should still go through everything) because I think the only changes I have other than my app are either rather small, but beneficial, or just comment changes and both of these will help.

**Comment by Noble-Mushtak** [comment]
Also, I'm sorry that this pull request has so many changes, it's just that having one `master` branch instead of multiple forks is the only way I could make my changes relevant and be able to make relevant contributions to this repo.

**Comment by Noble-Mushtak** [comment]
_Extremely_ good job on the CSS with the Client. Seriously and honestly impressed. I'm kind of bad at making user interfaces myself, but I think something like this will definitely work well.

Also, it would be much obliged if you used AJAX the first time instead of adding it in later. I've made the Client you added use AJAX because my computer seriously can't handle synchronous requests. I'm sorry, but it really can't, even for testing purposes. Furthermore, don't use jQuery when we don't have to. I like using jQuery for AJAX, but using it with simple DOM purposes when `.appendChild()` would do actually takes up more code, not less.

**Comment by Noble-Mushtak** [comment]
I think we should make sure we're using direct links to the KA contests and not links that are shorter but lead to re-directs. Using direct links without re-directs gives a better user experience.

**Comment by bytorbrynden** [comment]
> I think we should make sure we're using direct links to the KA contests and not links that are shorter but lead to re-directs. Using direct links without re-directs gives a better user experience.

Doing so would involve capturing more data, that we don't need. Am going to stick with the currently links for now.

**Edit**: I went ahead and switched to the longer CS links in https://github.com/Gigabyte-Giant/KA-Contest-Judging-System/commit/cafb929d08d0aaa6f4b0d88a22b0034ff52d1f23.

**Comment by Noble-Mushtak** [comment]
@Gigabyte-Giant No, we don't need to change anything in the databases. All I did in my repo was change something in the JavaScript file.

**Comment by Noble-Mushtak** [comment]
Ignore my deleted comment, I didn't see your commit. Also, that change is better, but we should still be using `https://www.khanacademy.org` because that's what that domain re-directs to. There's no reason to use that domain.

**Comment by bytorbrynden** [comment]
Good point. I addressed this in https://github.com/Gigabyte-Giant/KA-Contest-Judging-System/commit/3e607beacf883312117f5a86da8f4ce149dd7e4b.

**Comment by bytorbrynden** [comment]
Have you removed `getApi` from this? Since we have a wrapper for the API now, I don't see a need for it.

**Comment by Noble-Mushtak** [comment]
Of course. I removed `getApi()` a _long, long_ time ago.

**Comment by Noble-Mushtak** [comment]
This should be closed because it's no longer necessary.

**Comment by bytorbrynden** [comment]
> This should be closed because it's no longer necessary.

Can do.

**Pull request closed without merging**
