### PR TITLE
Fix improper use of a native DOM method

### PR DESCRIPTION
**Pull request by MrMagma**
Major changes
- None

Minor Changes
- Fixed improper use of `querySelector` replacing with `querySelectorAll` and a loop as necessary
- Fixed an edge bug where if the judgeOnly class was removed from the judging pane the entry page would break
- Updated Gitter badge so that it links to the proper URL now that our team name has changed

### CODE REVIEW

**Comment by bytorbrynden** [comment]
Am going to close, as you didn't submit a proper PR.

**Comment by bytorbrynden** [comment]
Read [this](https://trello.com/c/wc10Itso/53-required-code-reviews); it contains an example of how I want PRs to look.

**Comment by MrMagma** [comment]
That better?

**Comment by Gigabyte-Giant** [comment]
...a little, but not quite.

http://take.ms/8dXho

**Comment by bytorbrynden** [comment]
Yep, much better. Can you please resolve the merge conflicts?

**Comment by MrMagma** [comment]
Merge conflict fixed. The Gitter badge is now broken again though so you'll have to change that since changing it in a PR is a merge conflict for some reason.

**Comment by bytorbrynden** [comment]
Awesome, thanks! LGTM!

**Pull request merged**
