### PR TITLE
Giga's Refactoring and comment adding

### PR DESCRIPTION
**Pull request by bytorbrynden**
I'm working on [refactoring everything](https://trello.com/c/FHd6YSsv/43-refactor-everything).

This pull request contains all my work with refactoring and comment adding, and will not contain any new features.

**DO NOT MERGE THIS YET**!

### CODE REVIEW

**Comment by codeHusky** [comment]
Thanks for the cleanup.

**Comment by bytorbrynden** [comment]
Just a few notes on the main things I'm changing in this PR:
- I'm getting rid of **all** anonymous functions... While this does force us to write a few more lines of code here and there, I think it's the best approach to this, until I setup [Babel](https://babeljs.io) (so we can use EMCAScript 6 features).
- I'm cleaning up the source files-- by this, I mean I'm following my own style guide, and trying to stick very close to Khan Academy's [Javascript Style Guide](https://github.com/Khan/style-guides/blob/master/style/javascript.md) (in part-2 of my refactoring, I'll change everything that doesn't somewhat follow Khan Academy's JS style guide).
- I'm giving all variables more descriptive/unique names. Most of are variable names are fine as-is, with exception to the variables that we declare in loops. Variables such as `i`, won't be tolerated from now on, due to Javascript getting finicky every now and then.

A major note: When I merge this PR, a set of contribution guidelines is coming with it. These contribution guidelines **must be followed**, if you want any of your PRs to be merged...
This isn't me trying to be a project nazi, it's just me trying to keep this project organized, and as professional as possible.

**Comment by bytorbrynden** [comment]
...was going to go ahead and merge this, so we can start on 2.0, and I decided to run a few tests before I merged it, and as it turns out, somewhere along the way, I broke the `judgeEntry` function... Will attempt to fix, and then I'll merge.

**Comment by bytorbrynden** [comment]
I'm going to merge this shortly, however, I'll need to dig around a bit to figure out why the leaderboard never loads...

The only thing that has changed in `leaderboard.js`, is/are the comments and a bit of whitespace.

**Pull request merged**
