### PR TITLE
Fix CodeClimate Gripes

### PR DESCRIPTION
**Pull request by MrMagma**
Fix CodeClimate gripes (hopefully improving our score) while improving overall readability. Some "problems" were not fixed though, due to the fact that they are stupid and not actual problems (I'd be happy to not define functions in loops if you had a better way JSLint). I will be updating over the course of the week (/time it takes this PR to be merged) with readability and style improvements as well.

### CODE REVIEW

**Comment by bytorbrynden** [comment]
...I sure hope you didn't break anything.

**Comment by Noble-Mushtak** [comment]
It doesn't look like he changed anything important, just a bunch of indentation changes for new brackets/`if` loops and a few `==` changes here and there.

**Comment by bytorbrynden** [comment]
Yup, that's the only reason I merged it.

**Comment by MrMagma** [comment]
No functionality should have been changed. (Unless you were relying on type coercion)

**Comment by bytorbrynden** [comment]
No, we aren't.

**Pull request merged**
