### PR TITLE
Added More Documentation and Comments

### PR DESCRIPTION
**Pull request by Noble-Mushtak**
I am a [literate programmer](https://en.wikipedia.org/wiki/Literate_programming), so I write comments _wherever I code_ (except HTML), so I changed most of the JavaScript to have more comments. I also made lots of questions in my comments which can be found by looking at the `Files changed` in the tabs above, pressing <kbd>Ctrl+F</kbd>  or <kbd>Cmd+f</kbd>, and typing in "`Noble Mushtak:`". I also added `README.md`s to help with documentation. I didn't change `Extension`, though, because it looked like something separate and it was too big for me to go through it all.

I put the JavaScript in `tests/sync_test.html` in a separate `tests/sync_test.js` file because the JavaScript is so big, it should be a separate file. Also, we need to be using asynchronous HTTP requests, so I switched `fetchEntries()` and `sync()` in `Backend/sync.js` to asynchronous requests and made appropriate changes in `tests/sync_test.js`.

Also, in the root `README.md`, I added myself as a team member. Hopefully, I will count if you accept this pull request...

### CODE REVIEW

**Comment by bytorbrynden** [comment]
I too am a literate programmer; but I wrote this stuff in a fairly short amount of time.

The reason I didn't put the Javascript for tests in separate files, is because those files aren't going to be around for much longer; I wrote those simply to test a few things.

In the production "builds", all HTTP Requests will be asynchronous.

If you want, I'll add you to our Slack group, where we could further discuss you becoming a team member.

We're not accepting many people to help us, as we don't want to have to try and keep a large team organized.

**Comment by Noble-Mushtak** [comment]
OK, that's cool. I think we should always use AJAX even in testing, though, because the synchronous requests were too laggy for my computer. I don't know how to use Slack, but I'd be OK with joining one. Do I need to sign up for a Slack account or can I just give you my e-mail?

Also, I forgot to put this above, but I found the Firebase ID somewhere in `tests/sync_test.html` and I deleted it.

**Comment by bytorbrynden** [comment]
...I'll just need an email address; you'll receive instructions on how to join when I invite you.

**Comment by Noble-Mushtak** [comment]
OK, I gave you my e-mail on KA. Please tell me when you've copied it so I can delete the Tip/Thank.

**Comment by bytorbrynden** [comment]
Invited you. Thanks!

**Comment by Noble-Mushtak** [comment]
Got the e-mail. Thanks!

**Pull request closed without merging**
