### PR TITLE
All Important Changes from @Noble-Mushtak and @aikaikaik

### PR DESCRIPTION
**Pull request by Noble-Mushtak**
OK, so me (@Noble-Mushtak) and @aikaikaik have worked together on this repo to make some important changes:
- Add `README.md`s to all folders (although the one for `tests` has been excluded from this branch)
- Add more comments to the code and clean up some of the mistakes in the code (Read the comments to figure out what we did. Also, [this Trello card](https://trello.com/c/b3IxySwP/24-add-more-comments-to-javascript-code) will also help.)
- Add more local resources like `jquery.js` and `bootstrap.js` (Read the `README.md` to figure out why `bootstrap.css` wasn't included.)
- Get rid of `Backend/sync.js` since it's outdated (The deletion of `tests/sync_test.html` has not been included in this branch, but you can do that if you want to.)

@aikaikaik 's changes to `Client/stylesheets/main.css` have been excluded from this repo and any changes to `tests` has been excluded from this branch. These are all of and only the _important_ changes we made.

Please look at these changes and merge using Git _as soon as possible_. We will merge all changes from your repo into this branch until you do so because that way, I'll be dealing with resolving conflicts, not you. Thank you for looking at this pull request!

### CODE REVIEW

**Comment by Gigabyte-Giant** [comment]
...was about to merge; and then I noticed that *every single line* that I wrote, was marked as deleted; and replaced with stuff "you" wrote... This is odd, as all you did was add some comments.

**Comment by aikaikaik** [comment]
I believe this is because you use tabs, and we use double spaces.

**Comment by bytorbrynden** [comment]
Please use CDNs. The `Resources` folder is for items that have no CDNs.

Also, @aikaikaik and @Noble-Mushtak; please use tabs in this project from now on.

**Comment by bytorbrynden** [comment]
I'm going to go ahead and merge this; however, I have a list of things that I'm going to change.
- [x] Revert back to using CDNs
- [ ] ~~Go back to using jQuery instead of standard DOM methods.~~
- [ ] Change comments

As per this PR, I am also going to be publishing a list of contribution guidelines, so it'll be easier for me to merge PRs in the future.

**Comment by Noble-Mushtak** [comment]
Thank you for merging! However, if you're going to revert back to using jQuery, at least do not mix the DOM with jQuery. That was my biggest problem because you were doing something like `$(imageDiv).add(mediaObject).appendTo(imageDiv)` which is really complicated and unnecessary.

**Comment by bytorbrynden** [comment]
Sometimes it's easier to mix the DOM with jQuery; the code I wrote is no exception. Eventually, I'm going to be "optimizing" all of the source code for this project.

**Comment by Noble-Mushtak** [comment]
But in that case, isn't it indubitably easier to just do `imageDiv.appendChild(mediaObject);`? That's clearly less characters, less code, and easier to understand.

**Comment by bytorbrynden** [comment]
Indeed it probably is. Very good point. Sticking with your changes.

**Pull request merged**
