### PR TITLE
Added Lines of Code to Entry and Removed Unnecessary Code

### PR DESCRIPTION
**Pull request by Noble-Mushtak**
I did the following things:
- I added the number of lines of code each entry had in an `h4` element at the top of `entry.html`.
- I added sliders to `entry.html` using jQuery UI in `entry.js`.
- I commented out `entry.js` more.
- I got rid of unnecessary JavaScript and CSS that was trying to mimic a `<details>` element even though there was already a `<details>` element.
- I merged https://github.com/Team-Delta-KA/KA-Contest-Judging-System/pull/33.

### CODE REVIEW

**Comment by Noble-Mushtak** [comment]
Also, this required another AJAX request, so instead of making another nested function within a JSON object, I created a `loadEntry()` function with the call to `Contest_Judging_System.loadEntry()` and then called `loadEntry()` inside an AJAX request.

Preferably (and I know you already know this, @Gigabyte-Giant , I'm just telling everyone the plan), we should store the number of lines of code in Firebase, but we can't do that right now because the bot is hard to update (as @Gigabyte-Giant said).

**Comment by bytorbrynden** [comment]
I'll try and update the bot later today, or tomorrow. Will review the rest of this PR shortly.

**Comment by Noble-Mushtak** [comment]
UPDATE: Added sliders to `entry.js`.

**Comment by bytorbrynden** [comment]
Thanks for the PR!

**Pull request merged**
