### PR TITLE
Added "Display More Contests" Button

### PR DESCRIPTION
**Pull request by Noble-Mushtak**
This incorporates pull request #43 and adds a "Display More Contests" button to `/Client/` so only 20 contests are added at a time. This cuts down on lag.

### CODE REVIEW

**Comment by bytorbrynden** [comment]
Why did you re-add the auth code into `/admin/scripts/main.js`? I have `/admin/scripts/auth.js` for that.

**Comment by bytorbrynden** [comment]
Awesome job! I merged this. One thing I did do, however, is I'm using CDNs instead of holding the files in our `/Resources/` directory.

See https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/cf0212865a8e8d20ea6f20c1cc314acc5904a775.

**Comment by Noble-Mushtak** [comment]
I didn't re-add it into `main.js`. I thought you did that! I got rid of the re-adding in the `master` branch.

**Comment by bytorbrynden** [comment]
I'll remove it, don't worry.

**Edit**: Removed the auth code in https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/deb0b997104ba6d1668a2a6e1546b9e32b7b2f1e.

**Pull request merged**
