### PR TITLE
Switched to noUiSlider and Added Ability to Adjust Program Dimensions

### PR DESCRIPTION
**Pull request by Noble-Mushtak**
I switched to [noUiSlider](http://refreshless.com/nouislider/) instead of using jQuery UI and allowed people to [adjust programs to custom sizes](https://github.com/Team-Delta-KA/KA-Contest-Judging-System/issues/39), which was pretty simple.

However, I also changed the `console.log`s  and the invocation to `callback` in `Authentication_Login.logUserIn()` to be done inside of the `.doesUserExist()` callback because that's when the user is actually logged in/created. However, when this is done, it is easy to see that the user is never actually logged in because the `.doesUserExist()` callback is never called because, for some reason, the callback to `usersRef.once("value", ...)` is never called! I tried running the following script and it did not log anything:

```
var fbRef = new Firebase("https://contest-judging-sys.firebaseio.com");
var usersRef = fbRef.child("users");
usersRef.once("value", function(snapshot) { console.log(snapshot.val()); });
```

I have no idea why this isn't working, but it clearly isn't.

### CODE REVIEW

**Comment by bytorbrynden** [comment]
The reason that script didn't log anything, is because the `value` event is only fired once data has been queried from Firebase (short answer: You have no Firebase Query).

`Auth.js` is going to be removed soon, and replaced with a much better authentication system that I've been working on.

Will review the `noUiSlider` stuff whenever I get a chance.

**Comment by Noble-Mushtak** [comment]
Ah...Thanks for the explanation on `auth.js`!

**Comment by bytorbrynden** [comment]
I undid the merge of this PR, because it broke everything judging related (see screenshot).

http://take.ms/gOlgG

**Comment by Noble-Mushtak** [comment]
That shouldn't have happened and it's not happening on my version of the app. I got rid of all calls to `$(...).slider()` after getting rid of jQuery UI. You must've made other changes somewhere and added that call in, so you have to convert it to noUiSlider.

**Comment by Noble-Mushtak** [comment]
Why didn't you merge my changes to `entry.js` in? That's what messed everything up:
https://github.com/Team-Delta-KA/KA-Contest-Judging-System/blob/master/Client/scripts/entry.js#L168

**Comment by Noble-Mushtak** [comment]
It looks like for some reason, you had to merge it manually and you didn't merge my noUiSlider in. It got deleted during the merge: https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/ff911e356ed4d6faf35dae25a31f48b58aa763fc

**Comment by Noble-Mushtak** [comment]
Wait...You clearly merged my noUiSlider changes in. I don't see how that could've happened in `entry.js` because there is no `$(...).slider()`: https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/3a8423219e067e99b1e3ca17cbd557b55ccba7b8

**Pull request merged**
