### PR TITLE
Added More Login Buttons

### PR DESCRIPTION
**Pull request by Noble-Mushtak**
This is in response to #56 . The following is supposed to be a fix of this issue.

### CODE REVIEW

**Comment by Noble-Mushtak** [comment]
DO NOT merge this until there are no conflicts here. I will resolve the conflicts.

**Comment by bytorbrynden** [comment]
I wasn't planning on it.

**Comment by Noble-Mushtak** [comment]
OK, I merged our repos. Please look at this as soon as possible, but don't look at it _too_ soon. Especially do not look at it now because these changes need good review from someone else and we're all tired from a busy coding day. Look at all of the changes I made thoroughly and please check that I didn't break anything. I did check `/`, `/contest.html` (both Tomorrowland and another contest), `/entry.html` (both an entry to Tomorrowland and another contest), `/admin/`, and `/admin/new_contest.html` (yes, I tested submitting a new rubric to Tomorrowland and it worked).

I undid some of your changes, @Gigabyte-Giant, because while they weren't necessarily broken, they took up more code than they needed and in the long run, that extra code would be harder to maintain. Please tell me if my shortening of code broke anything. Thank you!

**Comment by bytorbrynden** [comment]
I can't merge this, as you got rid of my calls to `getAllRubrics`, which we need (unless I'm forgetting something).

The authentication changes look good, though!

**Comment by Noble-Mushtak** [comment]
No, I changed to to getRubricsForContests() and changed getRubricsForContests() to be like getAllRubrics(). Please look at the code and test it out.

**Comment by Noble-Mushtak** [comment]
Also, tell me if my change have any JavaScript errors here, on GitHub or Google Hangouts for today. Thanks!

**Pull request merged**
